/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PlateRouteImport } from './routes/plate'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LandRouteImport } from './routes/land'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/layout'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as FeedbackTrackRouteImport } from './routes/feedback/track'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsLayoutRouteImport } from './routes/_authenticated/settings/layout'
import { Route as AuthenticatedProductsLayoutRouteImport } from './routes/_authenticated/products/layout'
import { Route as AuthenticatedMindmapsLayoutRouteImport } from './routes/_authenticated/mindmaps/layout'
import { Route as AuthenticatedKanbanLayoutRouteImport } from './routes/_authenticated/kanban/layout'
import { Route as AuthenticatedFeedbackLayoutRouteImport } from './routes/_authenticated/feedback/layout'
import { Route as AuthenticatedClientsLayoutRouteImport } from './routes/_authenticated/clients/layout'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPrimeiroPassosIndexRouteImport } from './routes/_authenticated/primeiro-passos/index'
import { Route as AuthenticatedMindmapsIndexRouteImport } from './routes/_authenticated/mindmaps/index'
import { Route as AuthenticatedKanbanIndexRouteImport } from './routes/_authenticated/kanban/index'
import { Route as AuthenticatedIndicatorsIndexRouteImport } from './routes/_authenticated/indicators/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGamificationIndexRouteImport } from './routes/_authenticated/gamification/index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as FeedbackTrackReferenceNumberRouteImport } from './routes/feedback/track.$referenceNumber'
import { Route as FeedbackSubmitOrganizationSlugRouteImport } from './routes/feedback/submit.$organizationSlug'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedMindmapsMindmapIdRouteImport } from './routes/_authenticated/mindmaps/$mindmapId'
import { Route as AuthenticatedKanbanBoardIdRouteImport } from './routes/_authenticated/kanban/$boardId'
import { Route as AuthenticatedFeedbackDepartmentsRouteImport } from './routes/_authenticated/feedback/departments'
import { Route as AuthenticatedFeedbackDashboardRouteImport } from './routes/_authenticated/feedback/dashboard'
import { Route as AuthenticatedFeedbackCategoriesRouteImport } from './routes/_authenticated/feedback/categories'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedPrimeiroPassosAdminIndexRouteImport } from './routes/_authenticated/primeiro-passos/admin/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateRoute = PlateRouteImport.update({
  id: '/plate',
  path: '/plate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const FeedbackTrackRoute = FeedbackTrackRouteImport.update({
  id: '/feedback/track',
  path: '/feedback/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsLayoutRoute =
  AuthenticatedSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedProductsLayoutRoute =
  AuthenticatedProductsLayoutRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedMindmapsLayoutRoute =
  AuthenticatedMindmapsLayoutRouteImport.update({
    id: '/mindmaps',
    path: '/mindmaps',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedKanbanLayoutRoute =
  AuthenticatedKanbanLayoutRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedFeedbackLayoutRoute =
  AuthenticatedFeedbackLayoutRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedClientsLayoutRoute =
  AuthenticatedClientsLayoutRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsLayoutRoute,
  } as any)
const AuthenticatedPrimeiroPassosIndexRoute =
  AuthenticatedPrimeiroPassosIndexRouteImport.update({
    id: '/primeiro-passos/',
    path: '/primeiro-passos/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedMindmapsIndexRoute =
  AuthenticatedMindmapsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMindmapsLayoutRoute,
  } as any)
const AuthenticatedKanbanIndexRoute =
  AuthenticatedKanbanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKanbanLayoutRoute,
  } as any)
const AuthenticatedIndicatorsIndexRoute =
  AuthenticatedIndicatorsIndexRouteImport.update({
    id: '/indicators/',
    path: '/indicators/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedGamificationIndexRoute =
  AuthenticatedGamificationIndexRouteImport.update({
    id: '/gamification/',
    path: '/gamification/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFeedbackLayoutRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsLayoutRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const FeedbackTrackReferenceNumberRoute =
  FeedbackTrackReferenceNumberRouteImport.update({
    id: '/$referenceNumber',
    path: '/$referenceNumber',
    getParentRoute: () => FeedbackTrackRoute,
  } as any)
const FeedbackSubmitOrganizationSlugRoute =
  FeedbackSubmitOrganizationSlugRouteImport.update({
    id: '/feedback/submit/$organizationSlug',
    path: '/feedback/submit/$organizationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsLayoutRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsLayoutRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsLayoutRoute,
  } as any)
const AuthenticatedMindmapsMindmapIdRoute =
  AuthenticatedMindmapsMindmapIdRouteImport.update({
    id: '/$mindmapId',
    path: '/$mindmapId',
    getParentRoute: () => AuthenticatedMindmapsLayoutRoute,
  } as any)
const AuthenticatedKanbanBoardIdRoute =
  AuthenticatedKanbanBoardIdRouteImport.update({
    id: '/$boardId',
    path: '/$boardId',
    getParentRoute: () => AuthenticatedKanbanLayoutRoute,
  } as any)
const AuthenticatedFeedbackDepartmentsRoute =
  AuthenticatedFeedbackDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedFeedbackLayoutRoute,
  } as any)
const AuthenticatedFeedbackDashboardRoute =
  AuthenticatedFeedbackDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedFeedbackLayoutRoute,
  } as any)
const AuthenticatedFeedbackCategoriesRoute =
  AuthenticatedFeedbackCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFeedbackLayoutRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsLayoutRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsLayoutRoute,
  } as any)
const AuthenticatedPrimeiroPassosAdminIndexRoute =
  AuthenticatedPrimeiroPassosAdminIndexRouteImport.update({
    id: '/primeiro-passos/admin/',
    path: '/primeiro-passos/admin/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/clients': typeof AuthenticatedClientsLayoutRouteWithChildren
  '/feedback': typeof AuthenticatedFeedbackLayoutRouteWithChildren
  '/kanban': typeof AuthenticatedKanbanLayoutRouteWithChildren
  '/mindmaps': typeof AuthenticatedMindmapsLayoutRouteWithChildren
  '/products': typeof AuthenticatedProductsLayoutRouteWithChildren
  '/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feedback/track': typeof FeedbackTrackRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/feedback/categories': typeof AuthenticatedFeedbackCategoriesRoute
  '/feedback/dashboard': typeof AuthenticatedFeedbackDashboardRoute
  '/feedback/departments': typeof AuthenticatedFeedbackDepartmentsRoute
  '/kanban/$boardId': typeof AuthenticatedKanbanBoardIdRoute
  '/mindmaps/$mindmapId': typeof AuthenticatedMindmapsMindmapIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/feedback/submit/$organizationSlug': typeof FeedbackSubmitOrganizationSlugRoute
  '/feedback/track/$referenceNumber': typeof FeedbackTrackReferenceNumberRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/gamification': typeof AuthenticatedGamificationIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/indicators': typeof AuthenticatedIndicatorsIndexRoute
  '/kanban/': typeof AuthenticatedKanbanIndexRoute
  '/mindmaps/': typeof AuthenticatedMindmapsIndexRoute
  '/primeiro-passos': typeof AuthenticatedPrimeiroPassosIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/primeiro-passos/admin': typeof AuthenticatedPrimeiroPassosAdminIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feedback/track': typeof FeedbackTrackRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/feedback/categories': typeof AuthenticatedFeedbackCategoriesRoute
  '/feedback/dashboard': typeof AuthenticatedFeedbackDashboardRoute
  '/feedback/departments': typeof AuthenticatedFeedbackDepartmentsRoute
  '/kanban/$boardId': typeof AuthenticatedKanbanBoardIdRoute
  '/mindmaps/$mindmapId': typeof AuthenticatedMindmapsMindmapIdRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/feedback/submit/$organizationSlug': typeof FeedbackSubmitOrganizationSlugRoute
  '/feedback/track/$referenceNumber': typeof FeedbackTrackReferenceNumberRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/gamification': typeof AuthenticatedGamificationIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/indicators': typeof AuthenticatedIndicatorsIndexRoute
  '/kanban': typeof AuthenticatedKanbanIndexRoute
  '/mindmaps': typeof AuthenticatedMindmapsIndexRoute
  '/primeiro-passos': typeof AuthenticatedPrimeiroPassosIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/primeiro-passos/admin': typeof AuthenticatedPrimeiroPassosAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/_authenticated/clients': typeof AuthenticatedClientsLayoutRouteWithChildren
  '/_authenticated/feedback': typeof AuthenticatedFeedbackLayoutRouteWithChildren
  '/_authenticated/kanban': typeof AuthenticatedKanbanLayoutRouteWithChildren
  '/_authenticated/mindmaps': typeof AuthenticatedMindmapsLayoutRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsLayoutRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/feedback/track': typeof FeedbackTrackRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/feedback/categories': typeof AuthenticatedFeedbackCategoriesRoute
  '/_authenticated/feedback/dashboard': typeof AuthenticatedFeedbackDashboardRoute
  '/_authenticated/feedback/departments': typeof AuthenticatedFeedbackDepartmentsRoute
  '/_authenticated/kanban/$boardId': typeof AuthenticatedKanbanBoardIdRoute
  '/_authenticated/mindmaps/$mindmapId': typeof AuthenticatedMindmapsMindmapIdRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/feedback/submit/$organizationSlug': typeof FeedbackSubmitOrganizationSlugRoute
  '/feedback/track/$referenceNumber': typeof FeedbackTrackReferenceNumberRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/gamification/': typeof AuthenticatedGamificationIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/indicators/': typeof AuthenticatedIndicatorsIndexRoute
  '/_authenticated/kanban/': typeof AuthenticatedKanbanIndexRoute
  '/_authenticated/mindmaps/': typeof AuthenticatedMindmapsIndexRoute
  '/_authenticated/primeiro-passos/': typeof AuthenticatedPrimeiroPassosIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/primeiro-passos/admin/': typeof AuthenticatedPrimeiroPassosAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/clients'
    | '/feedback'
    | '/kanban'
    | '/mindmaps'
    | '/products'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/login'
    | '/auth/register'
    | '/feedback/track'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/errors/$error'
    | '/feedback/categories'
    | '/feedback/dashboard'
    | '/feedback/departments'
    | '/kanban/$boardId'
    | '/mindmaps/$mindmapId'
    | '/products/$productId'
    | '/products/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/feedback/submit/$organizationSlug'
    | '/feedback/track/$referenceNumber'
    | '/apps'
    | '/calendar'
    | '/chats'
    | '/clients/'
    | '/feedback/'
    | '/gamification'
    | '/help-center'
    | '/indicators'
    | '/kanban/'
    | '/mindmaps/'
    | '/primeiro-passos'
    | '/products/'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/primeiro-passos/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/login'
    | '/auth/register'
    | '/feedback/track'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/errors/$error'
    | '/feedback/categories'
    | '/feedback/dashboard'
    | '/feedback/departments'
    | '/kanban/$boardId'
    | '/mindmaps/$mindmapId'
    | '/products/$productId'
    | '/products/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/feedback/submit/$organizationSlug'
    | '/feedback/track/$referenceNumber'
    | '/apps'
    | '/calendar'
    | '/chats'
    | '/clients'
    | '/feedback'
    | '/gamification'
    | '/help-center'
    | '/indicators'
    | '/kanban'
    | '/mindmaps'
    | '/primeiro-passos'
    | '/products'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/primeiro-passos/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/_authenticated/clients'
    | '/_authenticated/feedback'
    | '/_authenticated/kanban'
    | '/_authenticated/mindmaps'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/login'
    | '/auth/register'
    | '/feedback/track'
    | '/_authenticated/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/feedback/categories'
    | '/_authenticated/feedback/dashboard'
    | '/_authenticated/feedback/departments'
    | '/_authenticated/kanban/$boardId'
    | '/_authenticated/mindmaps/$mindmapId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/feedback/submit/$organizationSlug'
    | '/feedback/track/$referenceNumber'
    | '/_authenticated/apps/'
    | '/_authenticated/calendar/'
    | '/_authenticated/chats/'
    | '/_authenticated/clients/'
    | '/_authenticated/feedback/'
    | '/_authenticated/gamification/'
    | '/_authenticated/help-center/'
    | '/_authenticated/indicators/'
    | '/_authenticated/kanban/'
    | '/_authenticated/mindmaps/'
    | '/_authenticated/primeiro-passos/'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/primeiro-passos/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  LandRoute: typeof LandRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PlateRoute: typeof PlateRoute
  TestRoute: typeof TestRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  FeedbackTrackRoute: typeof FeedbackTrackRouteWithChildren
  FeedbackSubmitOrganizationSlugRoute: typeof FeedbackSubmitOrganizationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plate': {
      id: '/plate'
      path: '/plate'
      fullPath: '/plate'
      preLoaderRoute: typeof PlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/feedback/track': {
      id: '/feedback/track'
      path: '/feedback/track'
      fullPath: '/feedback/track'
      preLoaderRoute: typeof FeedbackTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/mindmaps': {
      id: '/_authenticated/mindmaps'
      path: '/mindmaps'
      fullPath: '/mindmaps'
      preLoaderRoute: typeof AuthenticatedMindmapsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsLayoutRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsLayoutRoute
    }
    '/_authenticated/primeiro-passos/': {
      id: '/_authenticated/primeiro-passos/'
      path: '/primeiro-passos'
      fullPath: '/primeiro-passos'
      preLoaderRoute: typeof AuthenticatedPrimeiroPassosIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/mindmaps/': {
      id: '/_authenticated/mindmaps/'
      path: '/'
      fullPath: '/mindmaps/'
      preLoaderRoute: typeof AuthenticatedMindmapsIndexRouteImport
      parentRoute: typeof AuthenticatedMindmapsLayoutRoute
    }
    '/_authenticated/kanban/': {
      id: '/_authenticated/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof AuthenticatedKanbanIndexRouteImport
      parentRoute: typeof AuthenticatedKanbanLayoutRoute
    }
    '/_authenticated/indicators/': {
      id: '/_authenticated/indicators/'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof AuthenticatedIndicatorsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/gamification/': {
      id: '/_authenticated/gamification/'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AuthenticatedGamificationIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedFeedbackLayoutRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsLayoutRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/feedback/track/$referenceNumber': {
      id: '/feedback/track/$referenceNumber'
      path: '/$referenceNumber'
      fullPath: '/feedback/track/$referenceNumber'
      preLoaderRoute: typeof FeedbackTrackReferenceNumberRouteImport
      parentRoute: typeof FeedbackTrackRoute
    }
    '/feedback/submit/$organizationSlug': {
      id: '/feedback/submit/$organizationSlug'
      path: '/feedback/submit/$organizationSlug'
      fullPath: '/feedback/submit/$organizationSlug'
      preLoaderRoute: typeof FeedbackSubmitOrganizationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsLayoutRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsLayoutRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsLayoutRoute
    }
    '/_authenticated/mindmaps/$mindmapId': {
      id: '/_authenticated/mindmaps/$mindmapId'
      path: '/$mindmapId'
      fullPath: '/mindmaps/$mindmapId'
      preLoaderRoute: typeof AuthenticatedMindmapsMindmapIdRouteImport
      parentRoute: typeof AuthenticatedMindmapsLayoutRoute
    }
    '/_authenticated/kanban/$boardId': {
      id: '/_authenticated/kanban/$boardId'
      path: '/$boardId'
      fullPath: '/kanban/$boardId'
      preLoaderRoute: typeof AuthenticatedKanbanBoardIdRouteImport
      parentRoute: typeof AuthenticatedKanbanLayoutRoute
    }
    '/_authenticated/feedback/departments': {
      id: '/_authenticated/feedback/departments'
      path: '/departments'
      fullPath: '/feedback/departments'
      preLoaderRoute: typeof AuthenticatedFeedbackDepartmentsRouteImport
      parentRoute: typeof AuthenticatedFeedbackLayoutRoute
    }
    '/_authenticated/feedback/dashboard': {
      id: '/_authenticated/feedback/dashboard'
      path: '/dashboard'
      fullPath: '/feedback/dashboard'
      preLoaderRoute: typeof AuthenticatedFeedbackDashboardRouteImport
      parentRoute: typeof AuthenticatedFeedbackLayoutRoute
    }
    '/_authenticated/feedback/categories': {
      id: '/_authenticated/feedback/categories'
      path: '/categories'
      fullPath: '/feedback/categories'
      preLoaderRoute: typeof AuthenticatedFeedbackCategoriesRouteImport
      parentRoute: typeof AuthenticatedFeedbackLayoutRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsLayoutRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsLayoutRoute
    }
    '/_authenticated/primeiro-passos/admin/': {
      id: '/_authenticated/primeiro-passos/admin/'
      path: '/primeiro-passos/admin'
      fullPath: '/primeiro-passos/admin'
      preLoaderRoute: typeof AuthenticatedPrimeiroPassosAdminIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedClientsLayoutRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsLayoutRouteChildren: AuthenticatedClientsLayoutRouteChildren =
  {
    AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
    AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
    AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  }

const AuthenticatedClientsLayoutRouteWithChildren =
  AuthenticatedClientsLayoutRoute._addFileChildren(
    AuthenticatedClientsLayoutRouteChildren,
  )

interface AuthenticatedFeedbackLayoutRouteChildren {
  AuthenticatedFeedbackCategoriesRoute: typeof AuthenticatedFeedbackCategoriesRoute
  AuthenticatedFeedbackDashboardRoute: typeof AuthenticatedFeedbackDashboardRoute
  AuthenticatedFeedbackDepartmentsRoute: typeof AuthenticatedFeedbackDepartmentsRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
}

const AuthenticatedFeedbackLayoutRouteChildren: AuthenticatedFeedbackLayoutRouteChildren =
  {
    AuthenticatedFeedbackCategoriesRoute: AuthenticatedFeedbackCategoriesRoute,
    AuthenticatedFeedbackDashboardRoute: AuthenticatedFeedbackDashboardRoute,
    AuthenticatedFeedbackDepartmentsRoute:
      AuthenticatedFeedbackDepartmentsRoute,
    AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  }

const AuthenticatedFeedbackLayoutRouteWithChildren =
  AuthenticatedFeedbackLayoutRoute._addFileChildren(
    AuthenticatedFeedbackLayoutRouteChildren,
  )

interface AuthenticatedKanbanLayoutRouteChildren {
  AuthenticatedKanbanBoardIdRoute: typeof AuthenticatedKanbanBoardIdRoute
  AuthenticatedKanbanIndexRoute: typeof AuthenticatedKanbanIndexRoute
}

const AuthenticatedKanbanLayoutRouteChildren: AuthenticatedKanbanLayoutRouteChildren =
  {
    AuthenticatedKanbanBoardIdRoute: AuthenticatedKanbanBoardIdRoute,
    AuthenticatedKanbanIndexRoute: AuthenticatedKanbanIndexRoute,
  }

const AuthenticatedKanbanLayoutRouteWithChildren =
  AuthenticatedKanbanLayoutRoute._addFileChildren(
    AuthenticatedKanbanLayoutRouteChildren,
  )

interface AuthenticatedMindmapsLayoutRouteChildren {
  AuthenticatedMindmapsMindmapIdRoute: typeof AuthenticatedMindmapsMindmapIdRoute
  AuthenticatedMindmapsIndexRoute: typeof AuthenticatedMindmapsIndexRoute
}

const AuthenticatedMindmapsLayoutRouteChildren: AuthenticatedMindmapsLayoutRouteChildren =
  {
    AuthenticatedMindmapsMindmapIdRoute: AuthenticatedMindmapsMindmapIdRoute,
    AuthenticatedMindmapsIndexRoute: AuthenticatedMindmapsIndexRoute,
  }

const AuthenticatedMindmapsLayoutRouteWithChildren =
  AuthenticatedMindmapsLayoutRoute._addFileChildren(
    AuthenticatedMindmapsLayoutRouteChildren,
  )

interface AuthenticatedProductsLayoutRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsLayoutRouteChildren: AuthenticatedProductsLayoutRouteChildren =
  {
    AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
    AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
    AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  }

const AuthenticatedProductsLayoutRouteWithChildren =
  AuthenticatedProductsLayoutRoute._addFileChildren(
    AuthenticatedProductsLayoutRouteChildren,
  )

interface AuthenticatedSettingsLayoutRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsLayoutRouteChildren: AuthenticatedSettingsLayoutRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsLayoutRouteWithChildren =
  AuthenticatedSettingsLayoutRoute._addFileChildren(
    AuthenticatedSettingsLayoutRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedClientsLayoutRoute: typeof AuthenticatedClientsLayoutRouteWithChildren
  AuthenticatedFeedbackLayoutRoute: typeof AuthenticatedFeedbackLayoutRouteWithChildren
  AuthenticatedKanbanLayoutRoute: typeof AuthenticatedKanbanLayoutRouteWithChildren
  AuthenticatedMindmapsLayoutRoute: typeof AuthenticatedMindmapsLayoutRouteWithChildren
  AuthenticatedProductsLayoutRoute: typeof AuthenticatedProductsLayoutRouteWithChildren
  AuthenticatedSettingsLayoutRoute: typeof AuthenticatedSettingsLayoutRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedGamificationIndexRoute: typeof AuthenticatedGamificationIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedIndicatorsIndexRoute: typeof AuthenticatedIndicatorsIndexRoute
  AuthenticatedPrimeiroPassosIndexRoute: typeof AuthenticatedPrimeiroPassosIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedPrimeiroPassosAdminIndexRoute: typeof AuthenticatedPrimeiroPassosAdminIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedClientsLayoutRoute: AuthenticatedClientsLayoutRouteWithChildren,
  AuthenticatedFeedbackLayoutRoute:
    AuthenticatedFeedbackLayoutRouteWithChildren,
  AuthenticatedKanbanLayoutRoute: AuthenticatedKanbanLayoutRouteWithChildren,
  AuthenticatedMindmapsLayoutRoute:
    AuthenticatedMindmapsLayoutRouteWithChildren,
  AuthenticatedProductsLayoutRoute:
    AuthenticatedProductsLayoutRouteWithChildren,
  AuthenticatedSettingsLayoutRoute:
    AuthenticatedSettingsLayoutRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedGamificationIndexRoute: AuthenticatedGamificationIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedIndicatorsIndexRoute: AuthenticatedIndicatorsIndexRoute,
  AuthenticatedPrimeiroPassosIndexRoute: AuthenticatedPrimeiroPassosIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedPrimeiroPassosAdminIndexRoute:
    AuthenticatedPrimeiroPassosAdminIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface FeedbackTrackRouteChildren {
  FeedbackTrackReferenceNumberRoute: typeof FeedbackTrackReferenceNumberRoute
}

const FeedbackTrackRouteChildren: FeedbackTrackRouteChildren = {
  FeedbackTrackReferenceNumberRoute: FeedbackTrackReferenceNumberRoute,
}

const FeedbackTrackRouteWithChildren = FeedbackTrackRoute._addFileChildren(
  FeedbackTrackRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  LandRoute: LandRoute,
  OrganizationsRoute: OrganizationsRoute,
  PlateRoute: PlateRoute,
  TestRoute: TestRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  FeedbackTrackRoute: FeedbackTrackRouteWithChildren,
  FeedbackSubmitOrganizationSlugRoute: FeedbackSubmitOrganizationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
